name       : python-regex
version    : 2018.08.29
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/r/regex/regex-2018.08.29.tar.gz : b73cea07117dca888b0c3671770b501bef19aac9c45c8ffdb5bea2cca2377b0a
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
