name       : python-regex
version    : 2020.11.13
release    : 9
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2020.11.13.tar.gz : 83d6b356e116ca119db8e7c6fc2983289d87b27b3fac238cfe5dca529d884562
homepage   : https://bitbucket.org/mrabarnett/mrab-regex
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
