name       : python-regex
version    : 2021.11.2
release    : 12
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2021.11.2.tar.gz : 5e85dcfc5d0f374955015ae12c08365b565c6f1eaf36dd182476a4d8e5a1cdb7
homepage   : https://bitbucket.org/mrabarnett/mrab-regex
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
