name       : python-regex
version    : 2019.01.23
release    : 5
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2019.01.23.tar.gz : 73da7e021a969f8c8c4e7a8dad54193fde4db408b4c43cf8c37dbe6857c5b156
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
