name       : python-regex
version    : 2019.08.19
release    : 6
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2019.08.19.tar.gz : 587b62d48ca359d2d4f02d486f1f0aa9a20fbaf23a9d4198c4bed72ab2f6c849
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
