name       : python-regex
version    : 2022.1.18
release    : 16
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2022.1.18.tar.gz : 97f32dc03a8054a4c4a5ab5d761ed4861e828b2c200febd4e46857069a483916
homepage   : https://github.com/mrabarnett/mrab-regex
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    This regex implementation is backwards-compatible with the standard 're' module, but offers additional functionality.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
