name       : python-regex
version    : 2017.06.07
release    : 1
source     :
    - https://pypi.python.org/packages/94/0f/23f4e5a4d7b039c1a48a92af819bc594c41f0a1ae3f73532bcf8670d5c05/regex-2017.06.07.tar.gz : e45784bbe5a0ce4a954fbc5e0f72909798257241147271d4906bc617fd59261b
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re.
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
