name       : python-regex
version    : 2021.10.8
release    : 11
source     :
    - https://pypi.python.org/packages/source/r/regex/regex-2021.10.8.tar.gz : 26895d7c9bbda5c52b3635ce5991caa90fbb1ddfac9c9ff1c7ce505e2282fb2a
homepage   : https://bitbucket.org/mrabarnett/mrab-regex
license    : Python-2.0
component  : programming.python
summary    : Alternative regular expression module, to replace re
description: |
    Alternative regular expression module, to replace re.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
